# -*- coding: utf-8 -*-
"""Letsupgrade_Day1_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qXaLWKPRQekRewfltkRs1bZeuyFmWCp7
"""

import numpy as np

arr = np.random.randint(10,50,(3,5))

#printing last three elements of g second row 
print(arr[1][2:])

#printing last three elements of g second row 
print(arr[2][2:])
